version: 2
sources:
- name: public
  quoting:
    database: true
    schema: false
    identifier: false
  tables:
  - name: _airbyte_raw_boards
  - name: _airbyte_raw_cards
  - name: _airbyte_raw_lists
  - name: _airbyte_raw_users
